#!/bin/bash
while true; do
clear
echo "👑 [KING]DevSupport PANEL"
echo "1. Create User"
echo "2. Delete User"
echo "3. List Users"
echo "4. Online Users"
echo "5. Traffic"
echo "6. Domain"
echo "0. Exit"

read -p "Select: " opt

case $opt in
1) bash /etc/autopanel/core/user.sh create ;;
2) bash /etc/autopanel/core/user.sh delete ;;
3) bash /etc/autopanel/core/user.sh list ;;
4) bash /etc/autopanel/core/online.sh ;;
5) bash /etc/autopanel/core/traffic.sh ;;
6) bash /etc/autopanel/core/domain.sh ;;
0) exit ;;
esac
done
